version: "3.3"

services:
  fastapi:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 1g
  frontend:
    build:
      dockerfile: Dockerfile
      context: .
    command: ["python", "-m", "streamlit", "run", "src/frontend/streamlit_app.py", "--server.port", "8502"]
    ports:
      - "8502:8502"
    volumes:
      - ./src:/app/src
    depends_on:
      - fastapi