---
# fastapi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastapi-pvc
  namespace: final-project
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
